import type { ModelOption, StageInfo, DetectionResult } from './types';

export const MODELS: ModelOption[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    label: 'GPT-4o',
    provider: 'OpenAI',
    badge: 'OpenAI',
    badgeColor: 'bg-success-500/15 text-success-400 border-success-500/30',
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    label: 'Claude 3.5',
    provider: 'Anthropic',
    badge: 'Anthropic',
    badgeColor: 'bg-warning-500/15 text-warning-400 border-warning-500/30',
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    label: 'Gemini 1.5',
    provider: 'Google',
    badge: 'Google',
    badgeColor: 'bg-primary-500/15 text-primary-400 border-primary-500/30',
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    label: 'DeepSeek V3',
    provider: 'DeepSeek',
    badge: 'DeepSeek',
    badgeColor: 'bg-accent-500/15 text-accent-400 border-accent-500/30',
  },
];

export const STAGES: StageInfo[] = [
  {
    id: 'connecting',
    label: '建立连接',
    description: '连接目标服务 · GET /v1/models',
  },
  {
    id: 'authenticating',
    label: '身份验证',
    description: 'API Key 校验 · 权限确认',
  },
  {
    id: 'sending-request',
    label: '发送请求',
    description: '构造请求 · 注入鉴权头',
  },
  {
    id: 'receiving-response',
    label: '接收响应',
    description: '等待响应 · 读取 HTTP 状态码',
  },
  {
    id: 'parsing-stream',
    label: '解析流式',
    description: 'SSE 分块解析 · Token 计数',
  },
  {
    id: 'analyzing-latency',
    label: '延迟分析',
    description: '首字节 TTFT · 总耗时',
  },
  {
    id: 'checking-safety',
    label: '可用性判定',
    description: '鉴权 / 限流 / 网络状态判别',
  },
];

export const SIMULATED_RESULTS: Record<string, DetectionResult> = {
  'gpt-4o': {
    model: 'gpt-4o',
    endpoint: 'api.openai.com/v1/chat/completions',
    apiKeyMasked: 'sk-···7f2a',
    timestamp: new Date().toISOString(),
    status: 'healthy',
    overallScore: 92,
    latency: {
      dns: 12,
      tcp: 28,
      tls: 44,
      firstByte: 340,
      streamDuration: 2800,
      total: 3224,
    },
    streamChunks: [
      { index: 0, content: 'Hello', latencyMs: 340 },
      { index: 1, content: '! I', latencyMs: 420 },
      { index: 2, content: "'m here", latencyMs: 510 },
      { index: 3, content: 'to help', latencyMs: 680 },
      { index: 4, content: 'you with', latencyMs: 890 },
      { index: 5, content: 'any questions', latencyMs: 1200 },
      { index: 6, content: 'you might have', latencyMs: 1500 },
      { index: 7, content: 'today.', latencyMs: 1800 },
      { index: 8, content: ' What would', latencyMs: 2100 },
      { index: 9, content: 'you like to', latencyMs: 2400 },
      { index: 10, content: ' know?', latencyMs: 2800 },
    ],
    safetyChecks: [
      { name: 'API Key 有效性', status: 'pass', detail: 'Key 验证通过，权限范围正常' },
      { name: 'HTTPS 加密', status: 'pass', detail: 'TLS 1.3，强加密套件' },
      { name: '内容过滤', status: 'pass', detail: '响应内容安全，无违规标记' },
      { name: '速率限制', status: 'warn', detail: '接近 RPM 上限 (85%)，建议监控' },
      { name: '数据脱敏', status: 'pass', detail: '未检测到敏感信息泄露' },
    ],
    issues: [
      {
        level: 'warning',
        title: '速率限制接近上限',
        detail: '当前 RPM 使用率 85%，高峰时段可能触发 429 限流。建议实施请求队列或升级配额。',
        metric: '85% RPM',
      },
      {
        level: 'healthy',
        title: 'TTFT 表现优秀',
        detail: '首 Token 延迟 340ms，低于 P50 基准值 420ms，用户体验良好。',
        metric: '340ms',
      },
      {
        level: 'info',
        title: '建议启用流式响应',
        detail: '当前请求已使用 stream: true，用户感知延迟显著降低。',
      },
    ],
    responsePreview: "Hello! I'm here to help you with any questions you might have today. What would you like to know?",
    tokensIn: 24,
    tokensOut: 28,
  },
  'claude-3.5-sonnet': {
    model: 'claude-3.5-sonnet',
    endpoint: 'api.anthropic.com/v1/messages',
    apiKeyMasked: 'sk-ant-···3c1b',
    timestamp: new Date().toISOString(),
    status: 'healthy',
    overallScore: 88,
    latency: {
      dns: 18,
      tcp: 35,
      tls: 52,
      firstByte: 410,
      streamDuration: 3200,
      total: 3715,
    },
    streamChunks: [
      { index: 0, content: 'Hi', latencyMs: 410 },
      { index: 1, content: 'there!', latencyMs: 520 },
      { index: 2, content: ' How', latencyMs: 680 },
      { index: 3, content: ' can I', latencyMs: 900 },
      { index: 4, content: ' assist', latencyMs: 1100 },
      { index: 5, content: ' you', latencyMs: 1400 },
      { index: 6, content: ' today?', latencyMs: 1700 },
      { index: 7, content: ' Feel', latencyMs: 2000 },
      { index: 8, content: ' free to', latencyMs: 2400 },
      { index: 9, content: ' ask me', latencyMs: 2800 },
      { index: 10, content: ' anything.', latencyMs: 3200 },
    ],
    safetyChecks: [
      { name: 'API Key 有效性', status: 'pass', detail: 'Key 验证通过' },
      { name: 'HTTPS 加密', status: 'pass', detail: 'TLS 1.3' },
      { name: '内容过滤', status: 'pass', detail: '响应内容安全' },
      { name: '速率限制', status: 'pass', detail: 'RPM 使用率 42%' },
      { name: '数据脱敏', status: 'pass', detail: '无敏感信息泄露' },
    ],
    issues: [
      {
        level: 'healthy',
        title: '连接稳定性优秀',
        detail: 'TLS 握手 52ms，连接建立快速且稳定。',
        metric: '52ms TLS',
      },
      {
        level: 'info',
        title: 'Anthropic-Version 头部已设置',
        detail: '检测到 anthropic-version: 2023-06-01，API 版本兼容。',
      },
    ],
    responsePreview: 'Hi there! How can I assist you today? Feel free to ask me anything.',
    tokensIn: 22,
    tokensOut: 24,
  },
  'gemini-1.5-pro': {
    model: 'gemini-1.5-pro',
    endpoint: 'generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent',
    apiKeyMasked: 'AIza···9d4f',
    timestamp: new Date().toISOString(),
    status: 'degraded',
    overallScore: 74,
    latency: {
      dns: 22,
      tcp: 40,
      tls: 68,
      firstByte: 680,
      streamDuration: 4200,
      total: 5010,
    },
    streamChunks: [
      { index: 0, content: 'Sure', latencyMs: 680 },
      { index: 1, content: ', I', latencyMs: 920 },
      { index: 2, content: ' can', latencyMs: 1100 },
      { index: 3, content: ' help', latencyMs: 1500 },
      { index: 4, content: ' with', latencyMs: 1900 },
      { index: 5, content: ' that.', latencyMs: 2300 },
      { index: 6, content: ' Let', latencyMs: 2700 },
      { index: 7, content: ' me', latencyMs: 3100 },
      { index: 8, content: ' think', latencyMs: 3500 },
      { index: 9, content: ' about', latencyMs: 3900 },
      { index: 10, content: ' it.', latencyMs: 4200 },
    ],
    safetyChecks: [
      { name: 'API Key 有效性', status: 'pass', detail: 'Key 验证通过' },
      { name: 'HTTPS 加密', status: 'pass', detail: 'TLS 1.3' },
      { name: '内容过滤', status: 'pass', detail: '响应内容安全' },
      { name: '速率限制', status: 'warn', detail: 'RPM 使用率 78%' },
      { name: '数据脱敏', status: 'warn', detail: '检测到 Prompt 中包含邮箱地址' },
    ],
    issues: [
      {
        level: 'warning',
        title: 'TTFT 偏高',
        detail: '首 Token 延迟 680ms，超过 P75 基准值 550ms。用户可能感知到明显等待。',
        metric: '680ms TTFT',
      },
      {
        level: 'warning',
        title: 'Prompt 中检测到敏感数据',
        detail: '输入 Prompt 中包含邮箱地址，建议在发送前进行脱敏处理。',
        metric: 'PII 检测',
      },
      {
        level: 'info',
        title: '建议启用流式响应',
        detail: '检测到 stream: false，用户需等待完整响应才能看到结果。',
      },
    ],
    responsePreview: "Sure, I can help with that. Let me think about it.",
    tokensIn: 28,
    tokensOut: 22,
  },
  'deepseek-v3': {
    model: 'deepseek-v3',
    endpoint: 'api.deepseek.com/v1/chat/completions',
    apiKeyMasked: 'sk-···e8a1',
    timestamp: new Date().toISOString(),
    status: 'critical',
    overallScore: 58,
    latency: {
      dns: 35,
      tcp: 62,
      tls: 95,
      firstByte: 1200,
      streamDuration: 6800,
      total: 8192,
    },
    streamChunks: [
      { index: 0, content: 'I', latencyMs: 1200 },
      { index: 1, content: ' apologize', latencyMs: 1800 },
      { index: 2, content: ' for', latencyMs: 2400 },
      { index: 3, content: ' the', latencyMs: 3000 },
      { index: 4, content: ' delay', latencyMs: 3600 },
      { index: 5, content: '.', latencyMs: 4200 },
      { index: 6, content: ' How', latencyMs: 4800 },
      { index: 7, content: ' may', latencyMs: 5400 },
      { index: 8, content: ' I', latencyMs: 6000 },
      { index: 9, content: ' help?', latencyMs: 6800 },
    ],
    safetyChecks: [
      { name: 'API Key 有效性', status: 'pass', detail: 'Key 验证通过' },
      { name: 'HTTPS 加密', status: 'warn', detail: 'TLS 1.2，建议升级至 1.3' },
      { name: '内容过滤', status: 'pass', detail: '响应内容安全' },
      { name: '速率限制', status: 'fail', detail: '已触发 429 限流，请求被拒绝' },
      { name: '数据脱敏', status: 'pass', detail: '无敏感信息泄露' },
    ],
    issues: [
      {
        level: 'critical',
        title: '触发速率限制 (429)',
        detail: '当前 RPM 已超过配额上限，请求被拒绝。建议立即实施退避重试策略或升级 API 配额。',
        metric: '429 Rate Limit',
      },
      {
        level: 'critical',
        title: 'TTFT 严重超标',
        detail: '首 Token 延迟 1200ms，超过 P95 基准值 800ms。用户体验严重影响。',
        metric: '1200ms TTFT',
      },
      {
        level: 'warning',
        title: 'TLS 版本过低',
        detail: '当前使用 TLS 1.2，建议升级至 TLS 1.3 以获得更好的安全性和性能。',
      },
    ],
    responsePreview: 'I apologize for the delay. How may I help?',
    tokensIn: 20,
    tokensOut: 15,
  },
};
